/*
**	$VER: Strings.c (8.3.97)
**
**	Xtruder default English strings
**
**	Copyright (C) 1994-1997 Martin Wulffeld
**	All Rights Reserved
*/

#include	"Xtruder_Header.h"


/*
 * English strings
 */
struct AppString AS[] =
{
	{MSG_XTRUDER_INFO,"Xtruder %s\n\nCopyright © 1994-1997 Martin Wulffeld\nAll Rights Reserved\n\nPublic screen: %s\n   ARexx port: XTRUDER\n\n%s"},
	{MSG_AUTHOR_INFO,"To contact me write to one\nof the following:\n\n%s"},
	{MSG_XTRUDER_UNREGINFO,"This is an unregistered evaluation\nversion of Xtruder. If you use it for\nmore than 2 weeks you should register!\n\nPlease refer to documentation\nfor registration matters."},
	{MSG_REGISTEREDTO,"Registered to "},
	{MSG_UNREGISTERED,"Unregistered evaluation version"},
	{MSG_NOCANDO,"This function is not available in the\nunregistered version of Xtruder.\n\nPlease refer to documention\nfor registration matters"},
	
		/// Requester titles
	
	{MSG_REQ_INFO,"Xtruder Information"},
	{MSG_REQ_WARNING,"Xtruder Warning"},
	{MSG_REQ_ERROR,"Xtruder Error"},
	
		/// Gadget requester formats
	
	{MSG_GF_OKAY,"_Okay"},
	{MSG_GF_CANCEL,"_Cancel"},
	{MSG_GF_SELECT,"_Select"},
	{MSG_GF_YESNO,"_Yes|_No"},
	{MSG_GF_OKAYCANCEL,"_Okay|_Cancel"},
	{MSG_GF_CONTINUEABORT,"_Continue|_Abort"},
	{MSG_GF_LOAD,"_Load"},
	{MSG_GF_SAVE,"_Save"},
	{MSG_GF_CONTINUE,"_Continue"},
	
		/// Gadgets
	
	{MSG_GAD_OKAY,"_Okay"},
	{MSG_GAD_CANCEL,"_Cancel"},
	
		/// Miscellaneous
	
	{MSG_TL_SELECTFILESDRAWERS,"Select file(s) and drawer(s)"},
	{MSG_TL_SELECTFILES,"Select file(s)"},
	{MSG_TL_SELECTFILE,"Select a file"},
	{MSG_TL_SELECTPATH,"Select a path"},
	{MSG_TL_PRESPECIFIEDENTRIES,"Prespecified entries"},
	{MSG_CLOSEVISITORWINDOWS,"Xtruder is trying to close its screen.\nPlease close all (visitor) windows."},
	
		/// Errors
	
	{MSG_COULDNOTOPENFONT,"Could not open '%s' font, size %ld."},
	{MSG_COULDNOTOPENSCREEN,"Could not open screen."},
	{MSG_COULDNOTOPENWINDOW,"Could not open window."},
	{MSG_COULDNOTCREATEGUI,"Could not create GUI."},
	{MSG_NOTENOUGHMEMORY,"Not enough memory"},
	
		/// Startup
	
	{MSG_YOUNEEDTHESELIBS,"You need the following libraries:\n"},
	{MSG_INFOLIBVERSION,"\n %s version %ld"},
	{MSG_COULDNOTCREATECOMMODITY,"Could not create commodity."},
	{MSG_PATHDOESNOTEXIST,"The path '%s' does not exist.\nShould it be created ?"},
	{MSG_COULDNOTCREATEPATH,"Could not create the path '%s'."},
	{MSG_XTRUDERALREADYRUNNING,"Another copy of Xtruder is already running.\nPop to front ?"},
	
		/// File check
	
	{MSG_FC_ONEORMOREPATHSNOTPRESENT,"One or more paths were not found. Cannot start check."},
	{MSG_FC_CHECKINGPRESPECIFIED,"Checking prespecified: %s"},
	{MSG_FC_NOPRESPECIFIED,"No prespecified"},
	{MSG_FC_CHECKINGSPECIFIED,"Checking specified files and drawers"},
	{MSG_FC_READPROTECTIONREMOVED,"Read protection on '%s' removed"},
	{MSG_FC_COULDNOTREMOVEPROTECTION,"Could not remove read protection"},
	{MSG_FC_FILEPROTECTED,"'%s' is protected from reading"},
	{MSG_FC_FILEHASPBCBITS,"'%s' has PBC bits set"},
	{MSG_FC_FILEALREADYEXISTS,"'%s' already exists."},
	{MSG_FC_DELETEALLIN,"Delete all in '%s' ?"},
	{MSG_FC_DELETEEXTRACTEDFILE,"Delete extracted file '%s' ?"},
	{MSG_FC_GF_DELETEEXTRACTED,"Delete _all|_Delete|_Skip|Sk_ip all"},
	{MSG_FC_VIRUSFOUND,"'%s' is infected with the '%s' virus"},
	{MSG_FC_VIRUSFOUND_Q,"The file '%s' size %ld is\ninfected with the '%s' virus.\nWhat should be done with it ?"},
	{MSG_FC_VIRUSINARCHIVEFOUND_Q,"The file '%s' size %ld within the archive\n'%s' size %ld is infected with the '%s' virus.\n\nWhat should be done with the archive ?"},
	{MSG_FC_GF_VIRUSFOUNDREQUEST,"_Disable|D_elete|_Rename|_Comment|C_opy|_Nothing"},
	{MSG_FC_WHATTODOWITHCOPIEDFILE,"What do you want to do with the copied\nfile '%s' size %ld ?"},
	{MSG_FC_GF_VIRUSCOPIEDREQUEST,"_Disable|_Rename|_Comment|_Nothing"},
	{MSG_FC_COPYINGFILE,"Copying '%s' to '%s'"},
	{MSG_FC_COULDNOTCOPYFILETO,"Could not copy '%s' to '%s'"},
	{MSG_FC_FILEDISABLED,"'%s' disabled"},
	{MSG_FC_COULDNOTDISABLEFILE,"Could not disable '%s'"},
	{MSG_FC_FILEWILLBEDELETEDLATER,"'%s' will be deleted after the check"},
	{MSG_FC_FILEDELETED,"'%s' deleted"},
	{MSG_FC_COULDNOTDELETEFILE,"Could not delete '%s'"},
	{MSG_FC_FILERENAMED,"'%s' renamed to '%s'"},
	{MSG_FC_COULDNOTRENAMEFILE,"Could not rename '%s' to '%s'"},
	{MSG_FC_TL_RENAMEFILE,"Rename file"},
	{MSG_FC_ENTERNEWNAME,"Enter new name for '%s'"},
	{MSG_FC_FILECOMMENTED,"'%s' commented with '%s'"},
	{MSG_FC_COULDNOTCOMMENTFILE,"Could not comment '%s' with '%s'"},
	{MSG_FC_TL_COMMENTFILE,"Comment file"},
	{MSG_FC_VIRUSNAMECOMMENT,"Suggested comment is virusname\n'%s'"},
	{MSG_FC_ENTERCOMMENT,"Enter comment for '%s'"},
	{MSG_FC_FILECOPIED,"'%s' copied to '%s'"},
	{MSG_FC_COULDNOTCOPYFILE,"Could not copy '%s' to '%s'"},
	{MSG_FC_FILEENCRYPTEDCOPYING,"'%s' encrypted. Copying to '%s'"},
	{MSG_FC_FILEISNOTINFECTED,"'%s' is not infected"},
	{MSG_FC_FILECANONLYBEDELETED,"'%s' can only be deleted"},
	{MSG_FC_INFECTEDHUNKCODEREMOVEDFILE,"Infected hunk/code removed from file"},
	{MSG_FC_COULDNOTSAVEREPAIREDFILE,"Could not save repaired file"},
	{MSG_FC_NOACTIONTAKEN,"No action has been taken"},
	{MSG_FC_COULDNOTCHECKFILE,"Could not check file"},
	
		/// Unpacking
	
	{MSG_FILECRUNCHEDDECRUNCHIT,"'%s' size %ld\nis crunched with '%s'. Decrunch it ?"},
	{MSG_DECRUNCHINGFILE,"Decrunching: '%s' - %ld - %s"},
	{MSG_FILEDECRUNCHED,"'%s' decrunched - O: %ld  D: %ld"},
	{MSG_DECRUNCHERROR,"Decrunch error: %s"},
	{MSG_EXTRACTTHEARCHIVE,"Extract the archive '%s' size %ld ?"},
	{MSG_EXTRACTINGARCHIVE,"Extracting archive '%s'"},
	{MSG_CONTL_EXTRACTING,"Extracting '%s' size %ld"},
	{MSG_ARCHIVEEXTRACTED,"Archive '%s' extracted"},
	{MSG_NOTCRUNCHEDWITHSUPPORTED,"'%s' is not crunched with a supported cruncher"},
	{MSG_TL_ENTERPASSWORD,"Please enter password"},
	
		/// Bootblock GUI
	
	{MSG_BB_TL_BOOTBLOCK,"Bootblock"},
	{MSG_BB_GAD_SHOWDF0,"_Show DF0:"},
	{MSG_BB_GAD_SHOWDF1,"S_how DF1:"},
	{MSG_BB_GAD_SHOWDF2,"Sh_ow DF2:"},
	{MSG_BB_GAD_SHOWDF3,"Sho_w DF3:"},
	{MSG_BB_GAD_SHOWDMS,"Show _DMS..."},
	{MSG_BB_GAD_CHECKDF0,"Check DF_0:"},
	{MSG_BB_GAD_CHECKDF1,"Check DF_1:"},
	{MSG_BB_GAD_CHECKDF2,"Check DF_2:"},
	{MSG_BB_GAD_CHECKDF3,"Check DF_3:"},
	{MSG_BB_GAD_CHECKDMS,"Check D_MS..."},
	{MSG_BB_GAD_INSTALLDF0,"_Install DF0:"},
	{MSG_BB_GAD_INSTALLDF1,"I_nstall DF1:"},
	{MSG_BB_GAD_INSTALLDF2,"Ins_tall DF2:"},
	{MSG_BB_GAD_INSTALLDF3,"Inst_all DF3:"},
	{MSG_BB_GAD_STATUS,"Status"},
	{MSG_BB_GAD_BUFFER,"Buffer"},
	{MSG_BB_GAD_LOAD,"_Load..."},
	{MSG_BB_GAD_SAVE,"Sa_ve..."},
	
		/// Bootblock: Select type
	
	{MSG_BBT_TL_BOOTBLOCK,"Bootblock"},
	{MSG_BBT_SELECTBOOTBLOCK,"Select bootblock"},
	{MSG_BBT_1XOFS,"1._x OFS"},
	{MSG_BBT_13FFS,"1_.3 FFS"},
	{MSG_BBT_20OFS,"2._0 OFS"},
	{MSG_BBT_20FFS,"_2.0 FFS"},
	{MSG_BBT_20OFSINT,"2.0 _OFS International"},
	{MSG_BBT_20FFSINT,"2.0 _FFS International"},
	{MSG_BBT_30OFSCACHE,"3.0 OFS _Cache"},
	{MSG_BBT_30FFSCACHE,"_3.0 FFS Cache"},
	{MSG_BBT_CUSTOM,"Custom _bootblock"},
	{MSG_BBT_CUSTOMSELECT,"_Select custom bootblock..."},
	{MSG_BBT_BAR_SELECTBOOTBLOCKTYPE,"Select bootblock type"},
	
		/// Bootblock: Miscellaneous
	
	{MSG_TL_DRIVE,"Drive"},
	{MSG_SELECTDRIVE,"Select drive"},
	{MSG_BB_STA_CHECKINGBOOTBLOCK,"Checking bootblock in DF%ld:"},
	{MSG_BB_STA_INSTALLINGBOOTBLOCK,"Installing bootblock in DF%ld:"},
	{MSG_BB_STA_BOOTBLOCKINSTALLED,"Bootblock in DF%ld: installed"},
	{MSG_BB_STA_BOOTBLOCKFROMDMSARCHIVE,"Bootblock from DMS archive: '%s'"},
	{MSG_BB_STA_CUSTOMBOOTBLOCKFROM,"Custom bootblock from: '%s'"},
	{MSG_BB_STA_COULDNOTINSTALLBB,"Could not install bootblock to DF%ld:"},
	{MSG_BB_BUF_UNKNOWNBB,"Unknown bootblock in DF%ld:"},
	{MSG_BB_BUF_UNKNOWNBBDMS,"Unknown bootblock in '%s'"},
	{MSG_BB_BUF_UNKNOWNCUSTOMBB,"Unknown custom bootblock in '%s'"},
	{MSG_BB_BUF_NOTBOOTABLEBB,"Not a bootable bootblock in DF%ld:"},
	{MSG_BB_BUF_NOTBOOTABLEBBDMS,"Not a bootable bootblock in '%s'"},
	{MSG_BB_BUF_NOTBOOTABLECUSTOMBB,"Not a bootable bootblock in '%s'"},
	{MSG_BB_BUF_DISKINFECTED,"The bootblock in DF%ld: is infected with the '%s' virus."},
	{MSG_BB_BUF_DMSFILEINFECTED,"'%s' is infected with the '%s' virus"},
	{MSG_BB_BUF_CUSTOMBBINFECTED,"Custom bootblock '%s' is infected with the '%s' virus"},
	{MSG_BB_INS_INSTALLBOOTBLOCK,"Install bootblock to DF%ld: ?"},
	{MSG_BB_CHK_DISKINFECTED,"The bootblock in DF%ld: is infected with the\n'%s' virus. What do you want to do with it ?"},
	{MSG_BB_CHK_DMSFILEINFECTED,"The bootblock of the '%s' DMS archive is\ninfected with the '%s' virus.\nWhat do you want to with it ?"},
	{MSG_BB_CHK_GF_BBCURECHOICE,"_Install|_Save as binary|_Nothing"},
	{MSG_BB_CHK_GF_DMSCURECHOICE,"_Delete archive|_Save as binary|_Nothing"},
	{MSG_BB_TL_SAVEASBINARY,"Save as binary"},
	{MSG_BB_SAV_BBSAVEDASBINARY,"Bootblock saved as binary to '%s'"},
	{MSG_BB_SAV_COULDNOTSAVEBBASBINARY,"Could not save bootblock as binary to '%s'"},
	{MSG_BB_FILEISNOTADMSARCHIVE,"'%s' is not a DMS archive"},
	{MSG_BB_TL_SELECTDMSARCHIVE,"Select DMS archive"},
	{MSG_BB_TL_SELECTCUSTOMBOOTBLOCK,"Select custom bootblock"},
	
		/// Bootblock: File check
	
	{MSG_DMSFILEINFECTED_SHORT,"'%s' is infected with the '%s' bootblock virus"},
	{MSG_COULDNOTCHECKBOOTBLOCK,"Could not check bootblock of DMS archive '%s'"},
	
		/// Reports: Main reports interface
	
	{MSG_MRI_TL_REPORTS,"Reports"},
	{MSG_MRI_GAD_CREATE,"_Create"},
	{MSG_MRI_GAD_UPDATE,"_Update"},
	{MSG_MRI_GAD_CHECK,"Chec_k"},
	{MSG_MRI_GAD_DELETE,"_Delete"},
	{MSG_MRI_TL_CREATEREPORT,"Create report"},
	{MSG_MRI_BODY_CREATEREPORT,"Please enter name for this report"},
	{MSG_MRI_DELETEREPORT,"Delete '%s' ?"},
	
		/// Reports: Create report interface
	
	{MSG_CRI_TL_REPORTCREATION,"Report creation"},
	{MSG_CRI_GAD_STOP,"_Stop"},
	{MSG_CRI_GAD_PAUSE,"_Pause"},
	{MSG_CRI_REPORTEXISTSOVERWRITE,"A report with that filename already exists.\nOverwrite?"},
	{MSG_CRI_COULDNOTCREATEREPORT,"Could not create report."},
	{MSG_CRI_COULDNOTUPDATEREPORT,"Could not update report."},
	{MSG_CRI_COULDNOTCREATECRC,"Could not create CRC for '%s' - Not enough memory."},
	
		/// Reports: Check report interface
	
	{MSG_CHI_TL_REPORTCHECKING,"Report checking"},
	{MSG_CHI_GAD_PAUSE,"_Pause"},
	{MSG_CHI_GAD_STOP,"_Stop"},
	{MSG_CHI_GAD_SAVEHISTORY,"Save _history"},
	{MSG_CHI_CHECKINFO,"Files:  %6ld  Mismatches:  %6ld"},
	{MSG_CHI_REPORTCHECKINFO,"Files in report: %ld  Checked: %ld  Mismatches: %ld"},
	{MSG_CHI_FILEDOESNOTMATCH,"'%s' does not match with the current file."},
	{MSG_CHI_GF_REPORTMISMATCH,"_Copy to|C_opy all to|_Delete|_Ignore|Ignore _all"},
	{MSG_CHI_COULDNOTCHECKREPORT,"Could not check report."},
	{MSG_CHI_FILENOTFOUND,"'%s' was not found"},
	{MSG_CHI_CRCISWRONG,"'%s' - CRC is wrong"},
	{MSG_CHI_SIZEISWRONG,"'%s' - Size is wrong"},
	{MSG_CHI_DATEISWRONG,"'%s' - Date is wrong"},
	{MSG_CHI_PROTECTIONISWRONG,"'%s' - Protection is wrong"},
	{MSG_CHI_COMMENTISWRONG,"'%s' - Comment is wrong!"},
	{MSG_CHI_COULDNOTCHECKCRC,"'%s' - Could not check CRC"},
	
		/// History
	
	{MSG_TL_HISTORY,"History"},
	{MSG_ENTRIES,"Entries: %ld"},
	{MSG_TL_SAVEHISTORY,"Save history"},
	{MSG_COULDNOTSAVEHISTORY,"Could not save history"},
	{MSG_HISTORYSAVED,"History has been saved"},
	{MSG_HISTORYSAVEDANDFLUSHED,"History has been saved and flushed"},
	
		/// List known
	
	{MSG_LIKN_TL_KNOWNBOOTBLOCKVIRUSES,"Known bootblock viruses"},
	{MSG_LIKN_TL_KNOWNFILEBASEDVIRUSES,"Known file based viruses"},
	{MSG_LIKN_TL_KNOWNCRUNCHERS,"Known crunchers"},
	{MSG_LIKN_TL_KNOWNPATCHES,"Known patches"},
	{MSG_LIKN_TL_KNOWNFILETYPES,"Known file types"},
	{MSG_LIKN_VIRUSES,"Viruses: %ld"},
	{MSG_LIKN_CRUNCHERTYPES,"Cruncher types: %ld"},
	{MSG_LIKN_PATCHES,"Patches: %ld"},
	{MSG_LIKN_FILETYPES,"File types: %ld"},
	
		/// Memory: Miscellaneous
	
	{MSG_MEM_TL_LVOCHECK,"LVO check"},
	{MSG_MEM_LVOSTATISTICS,"Viruses: %ld  Known patches: %ld  Unknown: %ld"},
	{MSG_MEM_LIBRARYVECTORSINRAM,"Library vectors in RAM:"},
	{MSG_MEM_UNKNOWNPROGRAM,"Unknown program"},
	{MSG_MEM_LVOFORMAT,"    Offset          LVO        Description"},
	{MSG_MEM_VECTORSOKAY,"Vectors are okay"},
	{MSG_MEM_VECTORSNOTOKAY,"One or more vectors has a reference to RAM.\nThis could be virus.\nReset them?"},
	
	
		/// Memory: Show
	
	{MSG_MESW_TL_LIBRARIES,"Libraries"},
	{MSG_MESW_TL_DEVICES,"Devices"},
	{MSG_MESW_TL_RESOURCES,"Resources"},
	{MSG_MESW_TL_PORTS,"Ports"},
	{MSG_MESW_TL_SEMAPHORES,"Semaphores"},
	{MSG_MESW_TL_TASKS,"Tasks"},
	{MSG_MESW_TOTAL,"Total: %ld"},
	{MSG_MESW_NAME,"Name"},
	{MSG_MESW_ADDRESS,"Address"},
	{MSG_MESW_PRIORITY,"Pri"},
	{MSG_MESW_VERSION,"Version"},
	{MSG_MESW_TYPE,"Type"},
	{MSG_MESW_TASK,"Task"},
	{MSG_MESW_PROCESS,"Process"},
	{MSG_MESW_UNKNOWN,"Unknown"},
	
		/// System information
	
	{MSG_SYIN_TL_SYSTEMINFORMATION,"System information"},
	{MSG_SYIN_NOTFOUNDPLEASECONFIG,"Not found. Please configure."},
	{MSG_SYIN1, "Xtruder size:         %ld bytes"},
	{MSG_SYIN2, "Bootblock.library:    %2ld.%-2ld  Knows %ld bootblock viruses   %s"},
	{MSG_SYIN3, "FileID.library:       %2ld.%-2ld  Knows %ld file types"},
	{MSG_SYIN4, "filevirus.library:    %2ld.%-2ld  Knows %ld file viruses"},
	{MSG_SYIN5, "unpack.library:       %2ld.%-2ld  Knows %ld cruncher types"},
	{MSG_SYIN6, "xfdmaster.library:    %2ld.%-2ld  Knows %ld cruncher types"},
	{MSG_SYIN7, "xtruder.library:      %2ld.%-2ld  Knows %ld patches"},
	{MSG_SYIN8, "Archive extract path: %s"},
	{MSG_SYIN9, "File decrunch path:   %s"},
	{MSG_SYIN10,"Recheck files path:   %s"},
	
		/// Virus information
	
	{MSG_VI_TL_VIRUSINFORMATION,"Virus information"},
	{MSG_VI_DESCRIPTIONSPATH,"_Descriptions path"},
	{MSG_VI_EXTERNALVIEWER,"_External viewer"},
	{MSG_VI_SEARCHSTRING1,"Search string _1"},
	{MSG_VI_SEARCHSTRING2,"Search string _2"},
	{MSG_VI_SEARCHSTRING3,"Search string _3"},
	{MSG_VI_SEARCH,"_Search"},
	{MSG_VI_SHOWALL,"Show _all"},
	
		/// File check window
	
	{MSG_CW_TL_FILECHECK,"File check"},
	{MSG_CW_GAD_PAUSE,"_Pause"},
	{MSG_CW_GAD_STOP,"_Stop"},
	{MSG_CW_GAD_HISTORY,"_History"},
	{MSG_CW_MEMORYINFO1,"Available (chip): %9ld   Available (fast): %9ld"},
	{MSG_CW_MEMORYINFO2,"Largest (chip):   %9ld   Largest (fast):   %9ld"},
	{MSG_CW_CHECKINFO1,"Directories:    %6ld  Files:         %6ld  Checked:      %6ld"},
	{MSG_CW_CHECKINFO2,"Crunched:       %6ld  Decrunched:    %6ld"},
	{MSG_CW_CHECKINFO3,"Archived:       %6ld  Extracted:     %6ld"},
	{MSG_CW_CHECKINFO4,"Viruses found:  %6ld  Time:        %02ld:%02ld:%02ld"},
	{MSG_CW_OPERATIONPAUSED,"Operation paused"},
	
		/// Warnins
	
	{MSG_WA_NOTALLFILESWILLBECHECKED,"Not all files will be checked - Pattern '%s'"},
	{MSG_WA_FILESWITHPBCNOTCHECKED,"Files with PBC set will not be checked"},
	{MSG_WA_READPROTECTEDNOTCHECKED,"Read protected files will not be checked"},
	{MSG_WA_SYSTEMMESSAGESSUPPRESSED,"System messages will be suppressed"},
	{MSG_WA_CRUNCHEDEXENOTCHECKED,"Crunched executables are not checked"},
	{MSG_WA_CRUNCHEDDATANOTCHECKED,"Crunched data files are not checked"},
	{MSG_WA_ENCRYPTEDNOTCHECKED,"Encrypted files are not checked"},
	{MSG_WA_ARCHIVESNOTEXTRACTED,"Archives are not extracted"},
	{MSG_WA_NOTALLARCHIVESCHECKED,"Not all archived files will be checked - Pattern '%s'"},
	{MSG_WA_LHAARCHIVESNOTCHECKED,"LhA archives are not checked"},
	{MSG_WA_NOTALLLHAARCHIVESEXTRACTED,"Not all LhA archived files will be extracted"},
	{MSG_WA_LZXARCHIVESNOTCHECKED,"LZX archives are not checked"},
	{MSG_WA_NOTALLLZXARCHIVESEXTRACTED,"Not all LZX archived files will be extracted"},
	
		/// Trackdisk device errors
	
	{MSG_DISKWRITEPROTECTED,"Disk is write protected"},
	{MSG_NODISKINDRIVE,"No disk in drive"},
	{MSG_INVALIDDRIVE,"Invalid drive"},
	{MSG_DRIVEDOESNOTEXIST,"Drive does not exist"},
	{MSG_DRIVEBUSY,"Drive is busy"},
	
		/// Settings
	
	{MSG_AR_SETTINGS,"ARexx"},
	{MSG_AR_BAR_AREXX,"ARexx"},
	{MSG_AR_ADD,"_Add"},
	{MSG_AR_REMOVE,"_Remove"},
	{MSG_AR_UP,"_Up"},
	{MSG_AR_DOWN,"_Down"},
	{MSG_AR_SORTALPHABETICALLY,"_Sort alphabetically"},
	{MSG_AR_ITEMS,"Items"},
	{MSG_AR_NAME,"_Name"},
	{MSG_AR_SCRIPT,"Scr_ipt"},
	{MSG_AR_TL_ADD,"Add ARexx script"},
	{MSG_AR_ADDTEXT,"Please enter the name for the menu item"},
	{MSG_AR_GF_ADD,"_Okay|_Separator|_Cancel"},
	
	{MSG_BB_SETTINGS,"Bootblock"},
	{MSG_BB_BAR_BOOTBLOCK,"Bootblock"},
	{MSG_BB_CUSTOMBOOTBLOCK,"C_ustom bootblock"},
	{MSG_BB_CHECKINSERTEDDISKS,"C_heck inserted disks"},
	{MSG_BB_NOINTERFACE,"_No interface"},
	{MSG_BB_SELECTCUSTOM,"Select custom bootblock..."},
	
	{MSG_FCAR_SETTINGS,"Archives"},
	{MSG_FCAR_BAR_LHA,"LhA"},
	{MSG_FCAR_BAR_LZX,"LZX"},
	{MSG_FCAR_BAR_OUTPUT,"Output"},
	{MSG_FCAR_INTERNAL1,"Internal 1"},
	{MSG_FCAR_INTERNAL2,"Internal 2"},
	{MSG_FCAR_EXTRACTLHA,"Extract _LhA"},
	{MSG_FCAR_EXTRACTROUTINELHA,"_Extract routine"},
	{MSG_FCAR_LHAMAXSIZE,"LhA _max size"},
	{MSG_FCAR_EXTRACTLZX,"Extract L_ZX"},
	{MSG_FCAR_EXTRACTROUTINELZX,"E_xtract routine"},
	{MSG_FCAR_LZXMAXSIZE,"LZX m_ax size"},
	{MSG_FCAR_OUTPUT,"O_utput"},
	
	{MSG_FCCW_SETTINGS,"Check window"},
	{MSG_FCCW_BAR_CHECKWINDOW,"Check window"},
	{MSG_FCCW_AUTOCLOSE,"_Auto close"},
	{MSG_FCCW_MEMORYINFORMATION,"_Memory information"},
	{MSG_FCCW_CHECKINFORMATION,"Check _information"},
	{MSG_FCCW_HISTORY,"_History"},
	{MSG_FCCW_AUTOSCROLL,"A_uto scroll"},
	{MSG_FCCW_WARNINGS,"_Warnings"},
	
	{MSG_FCIN_SETTINGS,"Information"},
	{MSG_FCIN_BAR_INFORMATION,"Information"},
	{MSG_FCIN_SIZE,"Si_ze"},
	{MSG_FCIN_FILETYPE,"F_ile type"},
	{MSG_FCIN_PROTECTIONBITS,"Protection _bits"},
	{MSG_FCIN_DATE,"Da_te"},
	
	{MSG_FCMI_SETTINGS,"Miscellaneous"},
	{MSG_FCMI_BAR_MISCELLANEOUS,"Miscellaneous"},
	{MSG_FCMI_FILEFILTER,"_File filter"},
	{MSG_FCMI_ARCHIVEFILTER,"_Archive filter"},
	{MSG_FCMI_DOWITHVIRUSFOUND,"_Do with virus found"},
	{MSG_FCMI_DOWITHVIRUSCOPIED,"Do _with virus copied"},
	{MSG_FCMI_COMMENTFORVIRUS,"Co_mment for virus"},
	{MSG_FCMI_RENAMEEXTENSION,"Re_name extension"},
	{MSG_FCMI_PATHINDENTION,"Path _indention"},
	{MSG_FCMI_AUTODEPROTECT,"A_uto deprotect"},
	{MSG_FCMI_ENTERDIRECTORIES,"_Enter directories"},
	{MSG_FCMI_AUTOPATHCHECK,"Auto _path check"},
	{MSG_FCMI_SUPPRESSSYSTEMMESSAGES,"_Suppress system messages"},
	{MSG_FCMI_DISABLE,"Disable"},
	{MSG_FCMI_DELETE,"Delete"},
	{MSG_FCMI_RENAME,"Rename"},
	{MSG_FCMI_COMMENT,"Comment"},
	{MSG_FCMI_COPY,"Copy"},
	{MSG_FCMI_REQUEST,"Request"},
	{MSG_FCMI_NOTHING,"Nothing"},
	
	{MSG_FCPB_SETTINGS,"PBC"},
	{MSG_FCPB_BAR_PROTECTIONBITSFOR,"Protection Bits for Checked files"},
	{MSG_FCPB_PBCBITS,"PBC bits"},
	{MSG_FCPB_CHECKFILESWITHPBCSET,"Chec_k files with PBC set"},
	{MSG_FCPB_SETPBCONEXECUTABLES,"Set P_BC on executables"},
	{MSG_FCPB_SETPBCONARCHIVES,"Set PBC on archi_ves"},
	
	{MSG_FCPR_SETTINGS,"Prespecified"},
	{MSG_FCPR_BAR_PRESPECIFIED,"Prespecified"},
	{MSG_FCPR_ADD,"_Add"},
	{MSG_FCPR_REMOVE,"_Remove"},
	{MSG_FCPR_SORT,"_Sort"},
	
	{MSG_FCUN_SETTINGS,"Unpacking"},
	{MSG_FCUN_BAR_UNPACKING,"Unpacking"},
	{MSG_FCUN_WHENDECRUNCHINGUSE,"Whe_n decrunching use"},
	{MSG_FCUN_EXTRACTARCHIVES,"E_xtract archives"},
	{MSG_FCUN_ASKBEFOREEXTRACTING,"Ask be_fore extracting files"},
	{MSG_FCUN_ASKBEFOREDELETINGEXT,"Ask before deleting extracted f_iles"},
	{MSG_FCUN_DECRUNCHEXECUTABLES,"Decr_unch executables"},
	{MSG_FCUN_DECRUNCHDATAFILES,"Decrunch da_ta files"},
	{MSG_FCUN_ASKBEFOREDECRUNCHING,"Ask before decrunchin_g files"},
	{MSG_FCUN_ASKBEFOREDELETINGDEC,"Ask before deleting decrunched fi_les"},
	{MSG_FCUN_DECRUNCHENCRYPTED,"Decrunch encr_ypted files"},
	{MSG_FCUN_CHECKDMSBOOTBLOCK,"Check D_MS bootblock"},
	{MSG_FCUN_WHEN_UNPACKTHENXFD,"Unpack then XFD"},
	{MSG_FCUN_WHEN_XFDTHENUNPACK,"XFD then Unpack"},
	{MSG_FCUN_WHEN_ONLYUNPACK,"Only Unpack"},
	{MSG_FCUN_WHEN_ONLYXFD,"Only XFD"},
	
	{MSG_GU_SETTINGS,"GUI"},
	{MSG_GU_BAR_SCREEN,"Screen"},
	{MSG_GU_SCREENMODE,"_Screen mode"},
	{MSG_GU_PUBLICSCREENNAME,"_Public screen name"},
	{MSG_GU_SCREENFONT,"Screen _font"},
	{MSG_GU_TEXTFONT,"Te_xt font"},
	{MSG_GU_REQUESTERFONT,"_Requester font"},
	{MSG_GU_BACKGROUNDPATTERN,"_Background pattern"},
	{MSG_GU_PALETTE,"P_alette..."},
	{MSG_GU_SCROLLERWIDTH,"Scroller wid_th"},
	{MSG_GU_HIDEAPPICON,"_Hide AppIcon"},
	{MSG_TL_SELECTSCREENMODE,"Select screen mode"},
	{MSG_TL_SELECTPUBLICSCREEN,"Select public screen"},
	{MSG_TL_SELECTFONT,"Select font"},
	{MSG_TL_SELECTPATTERN,"Select pattern"},
	{MSG_TL_SETCOLORS,"Set colors"},
	{MSG_PUBLICSCREENS,"Public screens"},
	
	{MSG_HI_SETTINGS,"History"},
	{MSG_HI_BAR_HISTORY,"History"},
	{MSG_HI_BAR_ACTIONSTORECORD,"Actions to record"},
	{MSG_HI_HISTORYPATH,"_History path"},
	{MSG_HI_HISTORYFILE,"H_istory file"},
	{MSG_HI_MAXENTRIES,"_Max entries"},
	{MSG_HI_SAVEMETHOD,"_Save method"},
	{MSG_HI_USEDATEANDTIME,"_Use date and time as filename"},
	{MSG_HI_APPEND,"_Append"},
	{MSG_HI_REQUESTFILENAME,"_Request filename"},
	{MSG_HI_FILECHECK,"_File check"},
	{MSG_HI_AFTERACTION,"After action"},
	{MSG_HI_AFTERACTIONTHENFLUSH,"After action then flush"},
	{MSG_HI_DONOTSAVE,"Do not save"},
	{MSG_TL_SELECTHISTORYFILE,"Select history file"},
	
	{MSG_MI_SETTINGS,"Miscellaneous"},
	{MSG_MI_BAR_COMMODITY,"Commodity"},
	{MSG_MI_BAR_MISCELLANEOUS,"Miscellaneous"},
	{MSG_MI_POPKEY,"_Popkey"},
	{MSG_MI_PRIORITY,"Pr_iority"},
	{MSG_MI_POPUPATSTART,"Pop _up at start"},
	{MSG_MI_STAYHIDDEN,"_Stay hidden during checks"},
	
	{MSG_PA_SETTINGS,"Paths"},
	{MSG_PA_BAR_PATHS,"Paths"},
	{MSG_PA_ARCHIVEEXTRACTPATH,"_Archive extract path"},
	{MSG_PA_FILEDECRUNCHPATH,"_File decrunch path"},
	{MSG_PA_VIRUSPATH,"_Virus path"},
	{MSG_PA_RECHECKPATH,"_Recheck path"},
	{MSG_PA_AUTOCREATEABOVEPATHS,"Auto create above pat_hs"},
	{MSG_PA_AUTODELETEABOVEPATHS,"Au_to delete above paths"},
	{MSG_PA_GUIDEPATH,"_Guide path"},
	{MSG_PA_DESCRIPTIONSPATH,"D_escriptions path"},
	
	{MSG_ST_SETTINGS,"Startup"},
	{MSG_ST_BAR_AREXX,"ARexx"},
	{MSG_ST_BAR_STARTUP,"Startup"},
	{MSG_ST_STARTUPSCRIPT,"_Startup script"},
	{MSG_ST_EXECUTESTARTUPSCRIPT,"_Execute startup script"},
	{MSG_ST_CHECKPRESPECIFIED,"Check _prespecified"},
	{MSG_ST_CHECKVECTORS,"Check _vectors"},
	{MSG_ST_SHOWSYSTEMINFORMATION,"Show s_ystem information"},
	{MSG_TL_SELECTSCRIPT,"Select script"},
	
	{MSG_SAVESETTINGS,"Save settings ?"},
	{MSG_SETTINGSHAVECHANGED,"Settings have changed.\nDo you want to save them ?"},
	{MSG_GF_SETTINGSHAVECHANGED,"_Save|_Quit|_Cancel"},
	
		/// Menus
	
	{MSG_MU_TL_PROJECT,				"Project"},
	{MSG_MU_LISTKNOWN,				" \0List known"},
	{MSG_MU_LK_BOOTBLOCKVIRUSES,	" \0Bootblock viruses..."},
	{MSG_MU_LK_FILEBASEDVIRUSES,	" \0File based viruses..."},
	{MSG_MU_LK_CRUNCHERS,			" \0Crunchers..."},
	{MSG_MU_LK_PATCHES,				" \0Patches..."},
	{MSG_MU_LK_FILETYPES,			" \0File types..."},
	{MSG_MU_HELP,					" \0Help"},
	{MSG_MU_HP_INDEX,				" \0Index..."},
	{MSG_MU_HP_MENUS,				" \0Menus..."},
	{MSG_MU_HP_FILECHECK,			" \0File check..."},
	{MSG_MU_HP_BOOTBLOCKINTERFACE,	" \0Bootblock interface..."},
	{MSG_MU_HP_SETTINGS,			" \0Settings..."},
	{MSG_MU_HP_AREXX,				" \0ARexx..."},
	{MSG_MU_SYSTEMINFORMATION,		"?\0System information..."},
	{MSG_MU_HIDE,					"H\0Hide"},
	{MSG_MU_ABOUT,					" \0About"},
	{MSG_MU_AB_XTRUDER,				" \0Xtruder..."},
	{MSG_MU_AB_AUTHOR,				" \0Author..."},
	{MSG_MU_QUIT,					"Q\0Quit"},
	
	{MSG_MU_TL_FILES,				"Files"},
	{MSG_MU_CHECKPRESPECIFIED,		"P\0Check prespecified..."},
	{MSG_MU_LISTPRESPECIFIED,		"E\0List prespecified..."},
	{MSG_MU_CHECKFILES,				"C\0Check files..."},
	{MSG_MU_REPAIR,					"A\0Repair..."},
	{MSG_MU_SHOWCRC,				" \0Show CRC..."},
	{MSG_MU_REPORTS,				"R\0Reports..."},
	
	{MSG_MU_TL_BOOTBLOCK,			"Bootblock"},
	{MSG_MU_INTERFACE,				"N\0Interface..."},
	{MSG_MU_CHECK,					" \0Check"},
	{MSG_MU_CK_DF0,					"K\0DF0:..."},
	{MSG_MU_CK_DF1,					" \0DF1:..."},
	{MSG_MU_CK_DF2,					" \0DF2:..."},
	{MSG_MU_CK_DF3,					" \0DF3:..."},
	{MSG_MU_CK_DMS,					" \0DMS..."},
	{MSG_MU_INSTALL,				" \0Install"},
	{MSG_MU_IN_DF0,					"I\0DF0:..."},
	{MSG_MU_IN_DF1,					" \0DF1:..."},
	{MSG_MU_IN_DF2,					" \0DF2:..."},
	{MSG_MU_IN_DF3,					" \0DF3:..."},
	{MSG_MU_SHOW,					" \0Show"},
	{MSG_MU_SH_DF0,					"D\0DF0:..."},
	{MSG_MU_SH_DF1,					" \0DF1:..."},
	{MSG_MU_SH_DF2,					" \0DF2:..."},
	{MSG_MU_SH_DF3,					" \0DF3:..."},
	{MSG_MU_SH_DMS,					" \0DMS..."},
	
	{MSG_MU_TL_MEMORY,				"Memory"},
	{MSG_MU_CHECKVECTORS,			"O\0Check vectors..."},
	{MSG_MU_CHECKLVO,				"L\0Check LVO..."},
	{MSG_MU_CLEAR,					" \0Clear"},
	{MSG_MU_CR_ALL,					"*\0All..."},
	{MSG_MU_CR_COOLCAPTURE,			" \0Coolcapture..."},
	{MSG_MU_CR_COLDCAPTURE,			" \0Coldcapture..."},
	{MSG_MU_CR_WARMCAPTURE,			" \0Warmcapture..."},
	{MSG_MU_CR_KICKTAGPTR,			" \0KickTagPtr..."},
	{MSG_MU_CR_KICKMEMPTR,			" \0KickMemPtr..."},
	{MSG_MU_MEMSHOW,				" \0Show"},
	{MSG_MU_SW_LIBRARIES,			" \0Libraries..."},
	{MSG_MU_SW_DEVICES,				" \0Devices..."},
	{MSG_MU_SW_RESOURCES,			" \0Resources..."},
	{MSG_MU_SW_PORTS,				" \0Ports..."},
	{MSG_MU_SW_SEMAPHORES,			" \0Semaphores..."},
	{MSG_MU_SW_TASKS,				"T\0Tasks..."},
	
	{MSG_MU_TL_MISCELLANEOUS,		"Miscellaneous"},
	{MSG_MU_VIRUSINFORMATION,		"F\0Virus information..."},
	{MSG_MU_HISTORY,				" \0History"},
	{MSG_MU_HY_CLEAR,				" \0Clear"},
	{MSG_MU_HY_SHOW,				"W\0Show..."},
	{MSG_MU_HY_SAVE,				" \0Save..."},
	
	{MSG_MU_TL_SETTINGS,			"Settings"},
	{MSG_MU_SS_GUI,					"1\0GUI..."},
	{MSG_MU_SS_STARTUP,				"2\0Startup..."},
	{MSG_MU_SS_MISCELLANEOUS,		"3\0Miscellaneous..."},
	{MSG_MU_SS_PATHS,				"4\0Paths..."},
	{MSG_MU_SS_HISTORY,				"5\0History..."},
	{MSG_MU_SS_BOOTBLOCK,			"6\0Bootblock..."},
	{MSG_MU_SS_AREXX,				"7\0ARexx..."},
	{MSG_MU_SS_FILECHECK,			" \0File check..."},
	{MSG_MU_SSFC_PRESPECIFIED,		"8\0Prespecified..."},
	{MSG_MU_SSFC_MISCELLANEOUS,		"9\0Miscellaneous..."},
	{MSG_MU_SSFC_UNPACKING,			"0\0Unpacking..."},
	{MSG_MU_SSFC_ARCHIVES,			"!\0Archives..."},
	{MSG_MU_SSFC_INFORMATION,		"#\0Information..."},
	{MSG_MU_SSFC_PBC,				"%\0PBC..."},
	{MSG_MU_SSFC_CHECKWINDOW,		"&\0Check window..."},
	{MSG_MU_SS_LOAD,				" \0Load..."},
	{MSG_MU_SS_SAVE,				"V\0Save..."},
	{MSG_MU_SS_SAVEAS,				" \0Save as..."},
	
	{MSG_MU_TL_AREXX,				"ARexx"},
	{MSG_MU_EXECUTEAREXXSCRIPT,		"X\0Execute script..."},
	
		/// End marker
	
	{0,								""},
};
